### ISSUE TITLE
Almost 3GB ram used in prune mode

### ISSUE THREAD

**Issue by skironDotNet** [digibyte/digibyte#175] opened 2019-01-31 00:02 UTC
running DGB in blockchian prune mode -prune flag and I see 34% mem use in 8GB VPS, this is too much

not sure if prune mode matters, may be a duplicate of https://github.com/digibyte/digibyte/issues/144

**Comment by ChillingSilence** [comment] 2019-01-31 00:14
Confirmed duplicate of #144 , it's the fact we have *so* many blocks right now that's causing this.
34% is 2.7GB which is to be expected. Please follow the progress on #144

**Closed as completed by ChillingSilence** 2019-01-31 00:14 UTC
Labels: duplicate
